### ISSUE TITLE
Add `mountpoint` key to iconSet

### ISSUE THREAD

**Issue by schloram** [itplusx/flexible_pages#25]
There is also an mountpoint variant of a page (if `content_from_pid` is set). We should consider to make this editable with a `mountpointIcon` option.

Example: 
```yaml
dokType: 87
label: 'My Custom pageType'
iconSet:
  defaultIcon:
    # 'source' or ''
  hideInMenuIcon:
  rootPageIcon:
  mountpointIcon:
```
